/*
 * AllowedDomainsInfo.as
 *
 * This file was generated by asSchema.
 * http://www.wersling.com
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 */
package net.manaca.application.config.model
{
import net.manaca.xml.XMLNode;
import net.manaca.xml.types.*;

/**
 * The allowed domain list
 * @author v-seanzo
 * 
 */    
public class AllowedDomainsInfo extends XMLNode
{

    private const namespaceURI:String = "www.manaca.net";
    
    /**
     * Constructs a new AllowedDomainsInfo instance. 
     * @param node The XML to create the new Node object. 
     * @return 
     * 
     */
    public function AllowedDomainsInfo(node:XML = null)
    {
        if (node == null)
        {
            node = <AllowedDomains xmlns="www.manaca.net"/>;
        }
        super(node);
    }
    
    /**
     * Add a The domain. 
     */    
    public function adddomain(value:String):void
    {
        var count:uint = getdomainCount();
        if (count < getdomainMaxCount())
        {
            addChild(ELEMENT, namespaceURI, 'Level', new XML('<domain>' + value + '</domain>'));
        }
        else
        {
            throw new Error('Exceed the maximum allowable value!');
        }
    }
    
    /**
     * Gets a The domain. 
     * @return a The domain. 
     */    
    public function get domain():String
    {
        var result:* = getdomainAt(0);
        if(result)
        {
            return result.getValue();
        }
        else 
        {
            return result;
        }
    }
    
    /**
     * Gets all The domain. 
     * @return all The domain. 
     */    
    public function get domainList():Array
    {
        var result:Array = new Array();
        var len:uint = getdomainCount();
        for (var i:uint = 0 ; i < len ; i ++ )
        {
            result.push(getdomainAt(i));
        }
        return result;
    }
    
    /**
     * Gets a The domain by index. 
     * @return 
     */    
    public function getdomainAt(index:int):SchemaString
    {
        var node:XML = getChildAt(ELEMENT, namespaceURI, 'domain', index);
        if (node)
        {
            return new SchemaString(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a The domain. 
     */    
    public function set domain(value:String):void
    {
        setdomainAt(0, new SchemaString(value));
    }
    
    /**
     * Sets a The domain by index. 
     * @return 
     */    
    public function setdomainAt(index:int, value:SchemaString):void
    {
        if (value)
        {
            setChildAt(ELEMENT, namespaceURI, 'domain', index, value.node);
        }
        else
        {
            setChildAt(ELEMENT, namespaceURI, 'domain', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the minimum count of the domain. 
     * @return a Number that defines the minimum count of the domain. 
     */    
    public function getdomainMinCount():Number
    {
        return 0;
    }
    
    /**
     * Gets a Number that defines the maximal count of the domain. 
     * @return a Number that defines the maximal count of the domain. 
     */    
    public function getdomainMaxCount():Number
    {
        return Infinity;
    }
    
    /**
     * Boolean access to the existence of a designated domain. 
     * @return 
     */    
    public function hasdomain():Boolean
    {
        return getdomainCount() > 0;
    }
    
    /**
     * Gets a Number that defines the total count of the domain. 
     * @return a Number that defines the total count of the domain. 
     */    
    public function getdomainCount():Number
    {
        return getChildCount(ELEMENT, namespaceURI, 'domain');
    }
    
    public function clone():AllowedDomainsInfo
    {
        return new AllowedDomainsInfo(domNode.copy());
    }
    
    public function toString():String
    {
        var result:String = '------------AllowedDomainsInfo------------';
        result += '\ndomain:' + this.domain;
        return result;
    }
}
}