/*
 * FileTypeInfo.as
 *
 * This file was generated by asSchema.
 * http://www.wersling.com
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 */
package net.manaca.application.config.model
{
import net.manaca.xml.XMLNode;
import net.manaca.xml.types.*;

/**
 * FileTypeInfo
 * @author v-seanzo
 * 
 */	
public class FileTypeInfo extends SchemaString
{
    /** image */
    static public const IMAGE:String = "image";

    /** swf */
    static public const SWF:String = "swf";

    /** xml */
    static public const XML:String = "xml";

    /**
     * Constructs a new {@code FileTypeInfo} instance. 
     * @param newValue The String to create the new FileTypeInfo object. 
     * @return 
     * 
     */
    public function FileTypeInfo(newValue:String)
    {
    	super(newValue);
    }
    
}
}