/*
 * LoggingSettingsInfo.as
 *
 * This file was generated by asSchema.
 * http://www.wersling.com
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 */
package net.manaca.application.config.model
{
import net.manaca.xml.XMLNode;
import net.manaca.xml.types.*;

/**
 * logging settings info
 * @author v-seanzo
 * 
 */    
public class LoggingSettingsInfo extends XMLNode
{

    private const namespaceURI:String = "www.manaca.net";
    
    /**
     * Constructs a new LoggingSettingsInfo instance. 
     * @param node The XML to create the new Node object. 
     * @return 
     * 
     */
    public function LoggingSettingsInfo(node:XML = null)
    {
        if (node == null)
        {
            node = <LoggingSettings xmlns="www.manaca.net"/>;
        }
        super(node);
    }
    
    /**
     * Gets a The Output publisher. 
     * @return a The Output publisher. 
     */    
    public function get Output():OutputInfo
    {
        return getOutputAt(0);
    }
    
    /**
     * Gets a The Output publisher by index. 
     * @return 
     */    
    public function getOutputAt(index:int):OutputInfo
    {
        var node:XML = getChildAt(ELEMENT, namespaceURI, 'Output', index);
        if (node)
        {
            return new OutputInfo(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a The Output publisher. 
     */    
    public function set Output(value:OutputInfo):void
    {
        setOutputAt(0, value);
    }
    
    /**
     * Sets a The Output publisher by index. 
     * @return 
     */    
    public function setOutputAt(index:int, value:OutputInfo):void
    {
        if (value)
        {
            setChildAt(ELEMENT, namespaceURI, 'Output', index, value.node);
        }
        else
        {
            setChildAt(ELEMENT, namespaceURI, 'Output', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the total count of the Output. 
     * @return a Number that defines the total count of the Output. 
     */    
    public function getOutputCount():Number
    {
        return getChildCount(ELEMENT, namespaceURI, 'Output');
    }
    
    /**
     * Gets a The trace publicsher. 
     * @return a The trace publicsher. 
     */    
    public function get TracePublisher():TracePublisherInfo
    {
        return getTracePublisherAt(0);
    }
    
    /**
     * Gets a The trace publicsher by index. 
     * @return 
     */    
    public function getTracePublisherAt(index:int):TracePublisherInfo
    {
        var node:XML = getChildAt(ELEMENT, namespaceURI, 'TracePublisher', index);
        if (node)
        {
            return new TracePublisherInfo(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a The trace publicsher. 
     */    
    public function set TracePublisher(value:TracePublisherInfo):void
    {
        setTracePublisherAt(0, value);
    }
    
    /**
     * Sets a The trace publicsher by index. 
     * @return 
     */    
    public function setTracePublisherAt(index:int, value:TracePublisherInfo):void
    {
        if (value)
        {
            setChildAt(ELEMENT, namespaceURI, 'TracePublisher', index, value.node);
        }
        else
        {
            setChildAt(ELEMENT, namespaceURI, 'TracePublisher', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the total count of the TracePublisher. 
     * @return a Number that defines the total count of the TracePublisher. 
     */    
    public function getTracePublisherCount():Number
    {
        return getChildCount(ELEMENT, namespaceURI, 'TracePublisher');
    }
    
    /**
     * Gets a The log function is enabled. 
     * @return a The log function is enabled. 
     */    
    public function get enabled():Boolean
    {
        var result:* = getenabledAt(0);
        if(result)
        {
            return result.getValue();
        }
        else 
        {
            return result;
        }
    }
    
    /**
     * Gets a The log function is enabled by index. 
     * @return 
     */    
    private function getenabledAt(index:int):SchemaBoolean
    {
        var node:XML = getChildAt(ATTRIBUTE, namespaceURI, 'enabled', index);
        if (node)
        {
            return new SchemaBoolean(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a The log function is enabled. 
     */    
    public function set enabled(value:Boolean):void
    {
        setenabledAt(0, new SchemaBoolean(value));
    }
    
    /**
     * Sets a The log function is enabled by index. 
     * @return 
     */    
    private function setenabledAt(index:int, value:SchemaBoolean):void
    {
        if (value)
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'enabled', index, value.node);
        }
        else
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'enabled', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the total count of the enabled. 
     * @return a Number that defines the total count of the enabled. 
     */    
    public function getenabledCount():Number
    {
        return getChildCount(ATTRIBUTE, namespaceURI, 'enabled');
    }
    
    /**
     * Gets a LogLevel. 
     * @return a LogLevel. 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    public function get LogLevel():LogLevelInfo
    {
        return getLogLevelAt(0);
    }
    
    /**
     * Gets a LogLevel by index. 
     * @return 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    private function getLogLevelAt(index:int):LogLevelInfo
    {
        var node:XML = getChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index);
        if (node)
        {
            return new LogLevelInfo(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a LogLevel. 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    public function set LogLevel(value:LogLevelInfo):void
    {
        setLogLevelAt(0, value);
    }
    
    /**
     * Sets a LogLevel by index. 
     * @return 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    private function setLogLevelAt(index:int, value:LogLevelInfo):void
    {
        if (value)
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index, value.node);
        }
        else
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the total count of the LogLevel. 
     * @return a Number that defines the total count of the LogLevel. 
     */    
    public function getLogLevelCount():Number
    {
        return getChildCount(ATTRIBUTE, namespaceURI, 'LogLevel');
    }
    
    public function clone():LoggingSettingsInfo
    {
        return new LoggingSettingsInfo(domNode.copy());
    }
    
    public function toString():String
    {
        var result:String = '------------LoggingSettingsInfo------------';
        result += '\nOutput:' + this.Output;
        result += '\nTracePublisher:' + this.TracePublisher;
        result += '\nenabled:' + this.enabled;
        result += '\nLogLevel:' + this.LogLevel;
        return result;
    }
}
}