/*
 * LogLevelInfo.as
 *
 * This file was generated by asSchema.
 * http://www.wersling.com
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 */
package net.manaca.application.config.model
{
import net.manaca.xml.XMLNode;
import net.manaca.xml.types.*;

/**
 * LogLevelInfo
 * @author v-seanzo
 * 
 */	
public class LogLevelInfo extends SchemaString
{
    /** all */
    static public const ALL:String = "all";

    /** debug */
    static public const DEBUG:String = "debug";

    /** info */
    static public const INFO:String = "info";

    /** warn */
    static public const WARN:String = "warn";

    /** error */
    static public const ERROR:String = "error";

    /** fatal */
    static public const FATAL:String = "fatal";

    /** off */
    static public const OFF:String = "off";

    /**
     * Constructs a new {@code LogLevelInfo} instance. 
     * @param newValue The String to create the new LogLevelInfo object. 
     * @return 
     * 
     */
    public function LogLevelInfo(newValue:String)
    {
    	super(newValue);
    }
    
}
}