/*
 * TracePublisherInfo.as
 *
 * This file was generated by asSchema.
 * http://www.wersling.com
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 */
package net.manaca.application.config.model
{
import net.manaca.xml.XMLNode;
import net.manaca.xml.types.*;

/**
 * The trace publicsher
 * @author v-seanzo
 * 
 */    
public class TracePublisherInfo extends XMLNode
{

    private const namespaceURI:String = "www.manaca.net";
    
    /**
     * Constructs a new TracePublisherInfo instance. 
     * @param node The XML to create the new Node object. 
     * @return 
     * 
     */
    public function TracePublisherInfo(node:XML = null)
    {
        if (node == null)
        {
            node = <TracePublisher xmlns="www.manaca.net"/>;
        }
        super(node);
    }
    
    /**
     * Gets a LogLevel. 
     * @return a LogLevel. 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    public function get LogLevel():LogLevelInfo
    {
        return getLogLevelAt(0);
    }
    
    /**
     * Gets a LogLevel by index. 
     * @return 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    private function getLogLevelAt(index:int):LogLevelInfo
    {
        var node:XML = getChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index);
        if (node)
        {
            return new LogLevelInfo(node);
        }
        else
        {
            return null;
        }
    }
    
    /**
     * Sets a LogLevel. 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    public function set LogLevel(value:LogLevelInfo):void
    {
        setLogLevelAt(0, value);
    }
    
    /**
     * Sets a LogLevel by index. 
     * @return 
     * @see net.manaca.application.config.model.LogLevelInfo
     */    
    private function setLogLevelAt(index:int, value:LogLevelInfo):void
    {
        if (value)
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index, value.node);
        }
        else
        {
            setChildAt(ATTRIBUTE, namespaceURI, 'LogLevel', index, value);
        }
    }
    
    /**
     * Gets a Number that defines the total count of the LogLevel. 
     * @return a Number that defines the total count of the LogLevel. 
     */    
    public function getLogLevelCount():Number
    {
        return getChildCount(ATTRIBUTE, namespaceURI, 'LogLevel');
    }
    
    public function clone():TracePublisherInfo
    {
        return new TracePublisherInfo(domNode.copy());
    }
    
    public function toString():String
    {
        var result:String = '------------TracePublisherInfo------------';
        result += '\nLogLevel:' + this.LogLevel;
        return result;
    }
}
}